[package]
name = "flux-depend"
version = "0.1.0"
authors = ["Stephen Herbein <herbein1@llnl.gov>"]
edition = "2018"

[dependencies.flux-rs]
git = "https://github.com/flux-framework/flux-rs"
branch = "master"
